[package]
name = "yew-app"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { version = "0.22.0", features = ["csr"] }
web-sys = { version = "0.3", features = ["HtmlInputElement"] }
log = "0.4"
wasm-logger = "0.2"